# -*- coding: utf-8 -*-
"""1. Math And Logical Operators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vwwdno38VzEPf4OIR1ClLZEuLm3m7b10

1. Arithmetic operators
"""

# lets take two values to perform arithmetic operations

a = 5
b = 5

add = a + b # addition
subs = a - b # substraction
div = a / b # division
modu = a % b # modulo (remainder)
flr_div = a // b # floor division
exp = a ** b # exponential

print("addition :", add)
print("substraction :", subs)
print("division : ", div)
print("modulo :", modu)
print("floor division :", flr_div)
print("exponent :",exp)

"""2. Logical Operator"""

# lets take some values to perform logical operations

print(5 > 2 and 6 > 5) # and  (both condition be true then its true)
print(5 < 2 or 6 > 5) # or (anu of the comdition must be true then its true )
print(not (2 < 5)) # not (if condition is not true then)

"""3. Comparison Operator"""

# lets take two values to perform comparison operations

a = 5
b = 5

print(a == b, ": equal") # true if both equal
print(a != b, ": not equal") # true if both are not equal
print(a > b, ": greater than") # true if a is greater than b
print(a < b, ": less than") # true if a is smaller thab b
print(a >= b, ": greater than or equal") # true if a is greater than or equal to b
print(a <= b, ": smaller than or equal") # true if a is smaller than or equal to b

"""4. membership Operator"""

a = "string"
print("st" in a)
print("st" not in a)

"""5. identify Operator"""

a = 5
b = 5
print(a is b)
print(a is not b)

"""6. Assignment Operator"""

# 13 assignment operators

x= 10

x += 5 # add and assign
print("Add and assign :",x)

x -= 3 # Subtract and assign
print("Subtract and assign : ",x)

x *= 2     # Multiply and assign
print("Multiply and assign :",x)

x //= 4    # Floor divide and assign
print("Floor divide and assign :",x)

x %= 3     # Modulus and assign
print("Modulus and assign :", x)

x **= 2    # Exponent and assign
print("Exponent and assign :",x)

x //= 2    # Floor divide and assign
print("Floor divide and assign : ",x)

x |= 3     # Bitwise OR and assign
print("Bitwise OR and assign :",x)

x ^= 3     # Bitwise XOR and assign
print("Bitwise XOR and assign :", x)

x >>= 1    # Right shift and assign
print("Right shift and assign :", x)

x <<= 1    # Left shift and assign
print("Left shift and assign :", x)

"""7. Bitwise Operator"""

a = 10  # Binary: 1010
b = 4   # Binary: 0100

# Bitwise AND
print('a & b =', a & b) # Expected: 0 (Binary: 0000)

# Bitwise OR
print('a | b =', a | b) # Expected: 14 (Binary: 1110)

# Bitwise XOR
print('a ^ b =', a ^ b) # Expected: 14 (Binary: 1110)

# Bitwise NOT
print('~a =', ~a)     # Expected: -11 (Binary: ...11110101)

# Bitwise Left Shift
print('a << 2 =', a << 2) # Expected: 40 (Binary: 101000)

# Bitwise Right Shift
print('a >> 2 =', a >> 2) # Expected: 2 (Binary: 0010)